import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";





const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: [ "400", "500", "600", "700", "800", "900"],
});



export const metadata: Metadata = {
  title: "Mini-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${inter.variable} bg-[#f5f5f5] [--pattern-fg:var(--color-gray-950)]/5 antialiased`}
      >
        
        <main className=" ">
        {/* <Header/>  */}
        {children}
        </main>
       
        
      </body>
    </html>
  );
}


// #f5f5f5